[package]
name = "zpm-parsers"
edition = "2021"

[dependencies]
itertools = "0.14.0"
pretty_assertions = "1.4.1"
rstest = "0.26.1"
serde_json = { version = "1.0.140", features = ["raw_value"] }
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
zpm-utils = { path = "../zpm-utils" }

[target.'cfg(not(target_pointer_width = "32"))'.dependencies]
sonic-rs = "0.5.1"
