[package]
name = "zpm-parsers"
edition = "2021"

[dependencies]
zpm-utils = { path = "../zpm-utils" }
sonic-rs = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
regex = "1.10.2"
thiserror = "1.0"
serde_json = "1.0.140"
erased-serde = "0.4.6"
rstest = "0.26.1"
pretty_assertions = "1.4.1"

[dev-dependencies]
indoc = "2.0"
