[package]
name = "zpm-parsers"
edition = "2021"

[dependencies]
itertools = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
serde_json = { workspace = true, features = ["raw_value"] }
serde_yaml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
zpm-utils = { workspace = true }

[target.'cfg(not(target_pointer_width = "32"))'.dependencies]
sonic-rs = { workspace = true }
