[package]
name = "zpm-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode_derive = { version = "2.0.0-rc.3" }
bincode = { version = "2.0.0-rc.3" }
clean-path = "0.2.1"
colored = "3.0.0"
napi = { version = "2.13.1", default-features = false, features = [] }
path-slash = "0.2.1"
radix_trie = "0.2.1"
serde_derive = { version = "1.0.163" }
serde_json = "1.0.124"
serde = { version = "1.0.163" }
sonic-rs = "0.5.1"
tokio = { version = "1.39.2", features = ["fs"] }
thiserror = "2.0.12"
shlex = "1.3.0"
similar = "2.7.0"
