[package]
name = "zpm-utils"
edition = "2021"

[dependencies]
base64 = { workspace = true }
blake2 = { workspace = true }
colored = { workspace = true }
zpm-ecow = { workspace = true }
hex = { workspace = true }
ouroboros = { workspace = true }
rkyv = { workspace = true, features = ["bytecheck"] }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sha1 = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
thiserror = { workspace = true }
shlex = { workspace = true }
similar = { workspace = true }
urlencoding = { workspace = true }
wax = { workspace = true }
erased-serde = { workspace = true }
num = { workspace = true }
rstest = { workspace = true }
indexmap = { workspace = true, features = ["serde"]}
timeago = { workspace = true }
fundu = { workspace = true }
zpm-macro-enum = { workspace = true }
