[package]
name = "zpm-utils"
edition = "2021"

[dependencies]
bincode_derive = { version = "2.0.0-rc.3" }
bincode = { version = "2.0.0-rc.3" }
blake2 = { version = "0.10.6" }
clean-path = "0.2.1"
colored = "3.0.0"
hex = "0.4.3"
napi = { version = "2.13.1", default-features = false, features = [] }
ouroboros = "0.18.5"
path-slash = "0.2.1"
radix_trie = "0.2.1"
serde_derive = { version = "1.0.163" }
serde_json = "1.0.145"
serde = { version = "1.0.163" }
sha1 = "0.10.6"
sha2 = "0.10.8"
tokio = { version = "1.39.2", features = ["fs"] }
thiserror = "2.0.12"
shlex = "1.3.0"
similar = "2.7.0"
urlencoding = "2.1.3"
wax = { git = "https://github.com/arcanis/wax.git" }
erased-serde = "0.4.6"
num = "0.4.3"
rstest = "0.26.1"
indexmap = {version = "2.11.0", features = ["serde"]}
timeago = "0.5.0"
