[package]
name = "zpm-switch"
version = "6.0.0-rc.13"
edition = "2021"

[[bin]]
name = "yarn"
path = "src/main.rs"

[dependencies]
clipanion = { workspace = true, features = ["serde"] }
regex = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["hickory-dns", "rustls-tls"] }
rkyv = { workspace = true, features = ["bytecheck"] }
serde_plain = { workspace = true }
serde_with = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
zpm-allocator = { workspace = true }
zpm-formats = { workspace = true }
zpm-macro-enum = { workspace = true }
zpm-parsers = { workspace = true }
zpm-semver = { workspace = true }
zpm-utils = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
zpm-ecow = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
