[package]
name = "zpm-switch"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "yarn"
path = "src/main.rs"

[dependencies]
bincode = {version = "2.0.0-rc.3", features = ["serde"] }
blake2 = { version = "0.10.6" }
clipanion = { git = "https://github.com/arcanis/clipanion-rs.git" }
hex = "0.4.3"
regex = "1.11.1"
reqwest = { version = "0.12.5", default-features = false, features = ["hickory-dns", "rustls-tls"] }
serde_plain = "1.0.2"
serde_with = "3.9.0"
serde = "1.0.219"
sonic-rs = "0.5.1"
thiserror = "2.0.12"
tokio = { version = "1.39.2", features = ["full"] }
zpm-ci = { path = "../zpm-ci" }
zpm-formats = { path = "../zpm-formats" }
zpm-macro-enum = { path = "../zpm-macro-enum" }
zpm-semver = { version = "0.1.0", path = "../zpm-semver" }
zpm-utils = { version = "0.1.0", path = "../zpm-utils" }
assert_cmd = "2.0.17"
predicates = "3.1.3"
chrono = "0.4.41"
