[package]
name = "zpm-switch"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = {version = "2.0.0-rc.3", features = ["serde"] }
blake2 = { version = "0.10.6" }
clipanion = { path = "../../../clipanion-rs/packages/clipanion" }
hex = "0.4.3"
regex = "1.11.1"
reqwest = { version = "0.12.5", features = ["gzip", "rustls-tls", "trust-dns"] }
serde_with = "3.9.0"
serde = "1.0.219"
sonic-rs = "0.5.0"
thiserror = "2.0.12"
tokio = { version = "1.39.2", features = ["full"] }
zpm-formats = { path = "../zpm-formats" }
zpm-macros = { version = "0.1.0", path = "../zpm-macros" }
zpm-semver = { version = "0.1.0", path = "../zpm-semver" }
zpm-utils = { version = "0.1.0", path = "../zpm-utils" }
