[package]
name = "zpm-allocator"
edition = "2024"

[dependencies]

[target.'cfg(all(target_os = "windows"))'.dependencies]
mimalloc = { workspace = true }

[target.'cfg(all(not(target_os = "windows"), not(target_os = "openbsd"), not(target_os = "freebsd"), any(target_arch = "x86_64", target_arch = "aarch64", target_arch = "powerpc64")))'.dependencies]
tikv-jemallocator = { workspace = true }