[package]
name = "zpm-git"
edition = "2024"

[dependencies]
bincode = { version = "2.0.0-rc.3" }
fancy-regex = "0.13.0"
rkyv = { version = "0.8", features = ["bytecheck"] }
serde = { version = "1.0.207", features = ["derive"] }
thiserror = "1.0.63"
urlencoding = "2.1.3"
zpm-semver = { path = "../zpm-semver" }
zpm-utils = { path = "../zpm-utils" }
