[package]
name = "zpm-git"
edition = "2024"

[dependencies]
fancy-regex = { workspace = true }
rkyv = { workspace = true, features = ["bytecheck"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
urlencoding = { workspace = true }
zpm-semver = { workspace = true }
zpm-utils = { workspace = true }
