[package]
name = "zpm-sync"
edition = "2021"

[dependencies]
itertools = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
zpm-formats = { workspace = true }
zpm-utils = { workspace = true }
