[package]
name = "zpm-formats"
version = "0.1.0"
edition = "2021"

[dependencies]
arca = { version = "0.14.0" }
bytes = "1.7.1"
crc32fast = "1.4.2"
flate2 = "1.0.31"
itertools = "0.13.0"
regex = "1.10.6"
thiserror = "1.0.63"
