[package]
name = "zpm-formats"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
crc32fast = "1.4.2"
flate2 = { version = "1.0.31", features = ["zlib-rs"] }
itertools = "0.13.0"
pnp = { git = "https://github.com/yarnpkg/pnp-rs.git", branch = "mael/pub-vpath" }
regex = "1.10.6"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
zpm-utils = { path = "../zpm-utils" }
