[package]
name = "zpm-formats"
edition = "2021"

[dependencies]
crc32fast = { workspace = true }
flate2 = { workspace = true, features = ["zlib-rs"] }
itertools = { workspace = true }
pnp = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
zerocopy = { workspace = true, features = ["derive"] }
zpm-utils = { workspace = true }
