[package]
name = "zpm-primitives"
version = "6.0.0-alpha.0"
edition = "2024"

[dependencies]
colored = { workspace = true }
regex = { workspace = true }
rkyv = { workspace = true, features = ["bytecheck"] }
serde_plain = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
zpm-git = { workspace = true }
zpm-macro-enum = { workspace = true }
zpm-semver = { workspace = true }
zpm-utils = { workspace = true }
zpm-ecow = { workspace = true }
rstest = { workspace = true }
globset = { workspace = true }
