[package]
name = "zpm-macro-enum"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.36"
regex = "1.10.6"
syn = "2.0.74"
zpm-macro-helpers = { path = "../zpm-macro-helpers" }
