[package]
name = "zpm-config"
version = "6.0.0-alpha.0"
edition = "2024"

[dependencies]
convert_case = "0.8.0"
serde_yaml = "0.9.34"
serde = { version = "1.0.207", features = ["derive"] }
shellexpand = "3.1.1"
sonic-rs = "0.5.1"
thiserror = "2.0.16"
zpm-ci = { path = "../zpm-ci" }
zpm-macro-enum = { path = "../zpm-macro-enum" }
zpm-primitives = { path = "../zpm-primitives" }
zpm-semver = { path = "../zpm-semver" }
zpm-utils = { path = "../zpm-utils" }
bincode = "2.0.1"

[build-dependencies]
convert_case = "0.8.0"
serde_with = "3.9.0"
serde = { version = "1.0.207", features = ["derive"] }
sonic-rs = "0.5.1"
