[package]
name = "zpm-config"
edition = "2024"

[dependencies]
convert_case = { workspace = true }
serde_yaml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
shellexpand = { workspace = true }
thiserror = { workspace = true }
zpm-formats = { workspace = true }
zpm-macro-enum = { workspace = true }
zpm-primitives = { workspace = true }
zpm-semver = { workspace = true }
zpm-utils = { workspace = true }

[build-dependencies]
convert_case = { workspace = true }
serde_with = { workspace = true }
serde = { workspace = true, features = ["derive"] }
zpm-parsers = { workspace = true }
