[package]
name = "zpm-config"
version = "6.0.0-alpha.0"
edition = "2024"

[dependencies]
castaway = "0.2.4"
convert_case = "0.8.0"
ouroboros = "0.18.5"
serde = { version = "1.0.207", features = ["derive"] }
shellexpand = "3.1.1"
sonic-rs = "0.5.1"
thiserror = "2.0.16"
wax = { git = "https://github.com/arcanis/wax.git" }
zpm-primitives = { path = "../zpm-primitives" }
zpm-utils = { path = "../zpm-utils" }

[build-dependencies]
convert_case = "0.8.0"
serde_with = "3.9.0"
serde = { version = "1.0.207", features = ["derive"] }
sonic-rs = "0.5.1"
