[package]
name = "zpm"
edition = "2024"

[[bin]]
name = "yarn-bin"
path = "src/main.rs"

[dependencies]
base64 = "0.22.0"
bincode = {version = "2.0.0-rc.3", features = ["serde"] }
bytes = "1"
chrono = { version = "0.4.38", features = ["serde"] }
dashmap = "6"
clipanion = { git = "https://github.com/arcanis/clipanion-rs.git", features = ["serde", "tokens"] }
colored = "3.0.0"
dialoguer = "0.11.0"
futures = "0.3.30"
git-url-parse = "0.4.5"
globset = "0.4.14"
http = "1.3.1"
http-body-util = "0.1"
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
itertools = "0.13.0"
open = "5.3.2"
rayon = "1.10.0"
reqwest = { version = "0.12.26", default-features = false, features = ["gzip", "http2", "hickory-dns", "rustls-tls"] }
regex = "1.10.6"
serde_with = "3.9.0"
serde_yaml = "0.9.34"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
tower = { version = "0.5.2", features = ["limit"] }
serde_json = "1.0.145"
serde = { version = "1.0.207", features = ["derive"] }
wax = { git = "https://github.com/arcanis/wax.git" }
zpm-config = { path = "../zpm-config" }
zpm-formats = { path = "../zpm-formats" }
zpm-git = { path = "../zpm-git" }
zpm-macro-enum = { path = "../zpm-macro-enum" }
zpm-parsers = { path = "../zpm-parsers" }
zpm-primitives = { path = "../zpm-primitives" }
zpm-semver = { path = "../zpm-semver" }
zpm-switch = { path = "../zpm-switch" }
zpm-sync = { path = "../zpm-sync" }
zpm-utils = { path = "../zpm-utils" }
brotli = "8.0.1"
env_logger = "0.11.8"
hickory-resolver = "0.25.2"
indexmap = {version = "2.11.0", features = ["serde"]}
sha2 = "0.10.8"
hex = "0.4.3"
p256 = "0.13.2"
spki = "0.7.3"
ring = "0.17.14"
url = "2.5.7"

[dev-dependencies]
divan = { version = "4.2.0", package = "codspeed-divan-compat" }

[[bench]]
name = "cli"
harness = false
