[package]
name = "zpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37", features = ["full"] }
reqwest = { version = "0.12.2", features = ["gzip", "rustls-tls", "trust-dns"] }
regex = "1.10.4"
once_cell = "1.19.0"
rstest = "0.18.2"
glob-match = "0.2.1"
# arca = { version = "0.7.0", features = ["serde"] }
arca = { path = "../../../arca-rs", features = ["serde"] }
memoize = "0.4.2"
thiserror = "1.0.58"
serde_json = "1.0.115"
serde = { version = "1.0.197", features = ["derive"] }
futures = "0.3.30"
async-recursion = "1.1.0"
fancy-regex = "0.13.0"
sonic-rs = "0.3.4"
criterion = { version = "0.5.1", features = ["async_tokio"] }
hyper-util = "0.1.3"
rustls = "0.23.4"
pest = "2.7.9"
pest_derive = "2.7.9"
zpm-macros = { path = "../zpm-macros" }
cached = { version = "0.49.3", features = ["async", "disk_store"] }
tar = "0.4.40"
flate2 = "1.0.28"
bytes = "1.6.0"
zip = "0.6.6"
bincode = "2.0.0-rc.3"
sha2 = "0.10.8"
itertools = "0.12.1"
hex = "0.4.3"
serde_yaml = "0.9.34"
blake2 = { version = "0.10.6" }
serde_with = "3.8.1"
clap = { version = "4.5.4", features = ["derive"] }
once_map = "0.4.18"
crc32fast = "1.4.2"
trust-dns = "0.23.2"
wax = { git = "https://github.com/arcanis/wax.git" }

[[bench]]
name = "json"
harness = false

[[bench]]
name = "install"
harness = false
