[package]
name = "zpm"
edition = "2024"

[[bin]]
name = "yarn-bin"
path = "src/main.rs"

[dependencies]
base64 = { workspace = true }
bytes = { workspace = true}
chrono = { workspace = true, features = ["serde"] }
dashmap = { workspace = true }
clipanion = { workspace = true, features = ["serde", "tokens"] }
colored = { workspace = true }
dialoguer = { workspace = true }
futures = { workspace = true }
git-url-parse = { workspace = true }
globset = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["server", "http1"] }
hyper-util = { workspace = true, features = ["tokio"] }
itertools = { workspace = true }
open = { workspace = true }
rayon = { workspace = true }
rkyv = { workspace = true, features = ["bytecheck"] }
reqwest = { workspace = true, default-features = false, features = ["gzip", "http2", "hickory-dns", "rustls-tls"] }
regex = { workspace = true }
serde_with = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true, features = ["limit"] }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
wax = { workspace = true }
zpm-config = { workspace = true }
zpm-formats = { workspace = true }
zpm-git = { workspace = true }
zpm-macro-enum = { workspace = true }
zpm-parsers = { workspace = true }
zpm-primitives = { workspace = true }
zpm-semver = { workspace = true }
zpm-switch = { workspace = true }
zpm-sync = { workspace = true }
zpm-utils = { workspace = true }
brotli = { workspace = true }
env_logger = { workspace = true }
hickory-resolver = { workspace = true }
indexmap = { workspace = true, features = ["serde"]}
sha2 = { workspace = true }
hex = { workspace = true }
p256 = { workspace = true }
spki = { workspace = true }
ring = { workspace = true }
url = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
divan = { workspace = true, package = "codspeed-divan-compat" }

[[bench]]
name = "cli"
harness = false
