[package]
name = "zpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
reqwest = { version = "0.12.5", features = ["gzip", "rustls-tls", "trust-dns"] }
regex = "1.10.6"
rstest = "0.22.0"
arca = { path = "../../../arca-rs", version = "0.8.0", features = ["serde"] }
thiserror = "1.0.63"
serde_json = "1.0.124"
serde = { version = "1.0.207", features = ["derive"] }
futures = "0.3.30"
fancy-regex = "0.13.0"
zpm-macros = { path = "../zpm-macros" }
flate2 = "1.0.31"
bytes = "1.7.1"
bincode = "2.0.0-rc.3"
sha2 = "0.10.8"
itertools = "0.13.0"
hex = "0.4.3"
serde_yaml = "0.9.34"
blake2 = { version = "0.10.6" }
serde_with = "3.9.0"
crc32fast = "1.4.2"
trust-dns = "0.23.2"
wax = { git = "https://github.com/arcanis/wax.git" }
clipanion = { path = "../../../clipanion-rs/packages/clipanion", version = "0.5.0" }
rand = "0.8.5"

[[bench]]
name = "json"
harness = false

[[bench]]
name = "install"
harness = false
