[package]
name = "zpm"
version = "6.0.0-alpha.0"
edition = "2021"

[[bin]]
name = "yarn-bin"
path = "src/main.rs"

[dependencies]
bytes = "1.7.1"
bincode = {version = "2.0.0-rc.3", features = ["serde"] }
blake2 = { version = "0.10.6" }
clipanion = { git = "https://github.com/arcanis/clipanion-rs.git" }
colored = "3.0.0"
fancy-regex = "0.13.0"
futures = "0.3.30"
globset = "0.4.14"
hex = "0.4.3"
http = "1.3.1"
itertools = "0.13.0"
rayon = "1.10.0"
reqwest = { version = "0.12.5", default-features = false, features = ["gzip", "http2", "hickory-dns", "rustls-tls"] }
regex = "1.10.6"
rstest = "0.22.0"
serde_with = "3.9.0"
serde_yaml = "0.9.34"
sha2 = "0.10.8"
sonic-rs = "0.5.1"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
serde_json = "1.0.124"
serde = { version = "1.0.207", features = ["derive"] }
urlencoding = "2.1.3"
wax = { git = "https://github.com/arcanis/wax.git" }
zpm-ci = { path = "../zpm-ci" }
zpm-formats = { path = "../zpm-formats" }
zpm-macros = { path = "../zpm-macros" }
zpm-parsers = { path = "../zpm-parsers" }
zpm-semver = { path = "../zpm-semver" }
zpm-switch = { path = "../zpm-switch" }
zpm-utils = { path = "../zpm-utils" }
pretty-duration = "0.1.1"
convert_case = "0.8.0"
serde_plain = "1.0.2"
brotli = "8.0.1"
env_logger = "0.11.8"
