[package]
name = "zpm-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
once_cell = "1.19.0"
proc-macro2 = "1.0.79"
quote = "1.0.36"
regex = "1.10.4"
rstest = "0.19.0"
syn = "2.0.58"
