[package]
name = "zpm-semver"
edition = "2021"

[dependencies]
rkyv = { workspace = true, features = ["bytecheck"] }
rstest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
zpm-utils = { workspace = true }
