name: 'Performance tests'

on:
  schedule:
  - cron: '0 2-23/4 * * *'
  push:
  workflow_dispatch:
    inputs:
      sendReport:
        description: 'Whether to send the stats to the Datadog dashboards'
        required: true
        default: 'false'
      hyperfineOptions:
        description: 'Options passed to Hyperfine'
        required: false
        default: ''

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        benchmark:
          - [Next.js, next]
          - [Gatsby, gatsby]

    name: 'Benchmarking ${{matrix.benchmark[0]}} w/ Yarn ZPM'
    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/actions/prepare
      with:
        target: x86_64-unknown-linux-musl
        profile: release-lto

    - name: Install Flamegraph
      run: |
        cargo install flamegraph@0.6.9

    - name: 'Install Hyperfine'
      run: |
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.10.0/hyperfine_1.10.0_amd64.deb
        sudo dpkg -i hyperfine_1.10.0_amd64.deb

    - name: 'Creates a temporary directory'
      run: |
        BENCH_DIR=$(mktemp -d)
        echo "BENCH_DIR=$BENCH_DIR" >> "$GITHUB_ENV"

    - name: 'Run the performance test'
      run: |
        bash scripts/bench-run.sh zpm '${{matrix.benchmark[1]}}' "$BENCH_DIR"

        if [[ '${{github.event_name}}' != 'push' && '${{github.event.inputs.sendReport}}' != 'false' ]]; then
          yarn node scripts/submit-bench-data.js zpm '${{matrix.benchmark[1]}}' "$BENCH_DIR"
        fi
      env:
        DD_API_KEY: ${{secrets.DD_API_KEY}}
        HYPERFINE_OPTIONS: ${{github.event.inputs.hyperfineOptions}}

    - name: 'Upload the flamegraph'
      uses: actions/upload-artifact@v4
      with:
        name: 'flamegraph-zpm-${{matrix.benchmark[1]}}'
        path: "$BENCH_DIR/flamegraphs/*"
