name: Code Check

on:
    push:

jobs:
    typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Running TypeScript
              run: |
                yarn tsc --build

    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Running Eslint
              run: |
                yarn eslint
