name: Tests

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-tracker:
    name: 'Running the test tracker'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: test-reports
      url: |
        ${{
          github.event_name == 'pull_request' &&
          format('https://iteratum.ai/examples/jest-ui/?url=https%3A%2F%2Frepo.yarnpkg.com%2Fbuilds%2Fzpm%2Fcommits%2F{0}%2Ftests&compareUrl=https%3A%2F%2Frepo.yarnpkg.com%2Fbuilds%2Fzpm%2Fcommits%2F{1}%2Ftests', github.sha, github.event.pull_request.base.sha) ||
          format('https://iteratum.ai/examples/jest-ui/?url=https%3A%2F%2Frepo.yarnpkg.com%2Fbuilds%2Fzpm%2Fcommits%2F{0}%2Ftests', github.sha)
        }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/build
        with:
          target: x86_64-unknown-linux-musl
          profile: release

      - name: Copy files to the standard local path
        run: |
          ln -s target/x86_64-unknown-linux-musl/release local

      - name: Clone the berry repo
        uses: actions/checkout@v4
        with:
          repository: yarnpkg/berry
          path: berry

      - name: Prepare Node
        uses: ./.github/actions/prepare-node

      - name: Generate the test report
        run: |
          yarn ./tests/acceptance-tests jest --json --outputFile=$(pwd)/report.json || true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.json
